/-
Copyright (c) 2024 Shengyang Xu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Shengyang Xu
-/
import Mathlib.Analysis.InnerProductSpace.PiL2

/-!
# ConicCaratheodory

## Main results

This file contains the proof of conic version of Caratheodory theorem.

-/

open Finset

variable {n : ℕ} {s : Finset ℕ} {V : ℕ → (EuclideanSpace ℝ (Fin n))}
variable {x : EuclideanSpace ℝ (Fin n)}

/- Nonnegative Coefficients -/
def quadrant : Set (ℕ → ℝ) := {x : ℕ → ℝ | ∀ i : ℕ, 0 ≤ x i}

/- Restrict domain to Finset ℕ -/
def coe (s: Finset ℕ) : s → ℕ := fun i ↦ i

/- Definition of cone with finite base -/
def cone (s : Finset ℕ) (V : ℕ → (EuclideanSpace ℝ (Fin n))) : Set (EuclideanSpace ℝ (Fin n)) :=
  (fun x ↦ Finset.sum s (fun i => x i • V i)) '' quadrant

/- An Alternative Proof of conic version of Caratheodory Theorem.
   Reference : https://courses.engr.illinois.edu/cs598csc/sp2010/Lectures/Lecture2.pdf Theorem 18.
   This lemma states that : If x is in the cone generated by Finset s whose elements are not
   linear independent, then it is in the cone generated by a strict subset of s -/
private lemma mem_conic_erase (s : Finset ℕ) (V : ℕ → (EuclideanSpace ℝ (Fin n)))
    (nidp : ¬LinearIndependent ℝ (V ∘ coe s)) (xincV : x ∈ cone s V) :
    ∃ y : s, x ∈ cone (s.erase y) V := by
  sorry

theorem conic_Caratheodory (s : Finset ℕ) (V : ℕ → (EuclideanSpace ℝ (Fin n))):
    ∀ x ∈ cone s V, ∃ τ : Finset ℕ,
    (τ ⊆ s) ∧ (x ∈ cone τ V) ∧ (LinearIndependent ℝ (V ∘ coe τ)) ∧
    (∀ σ : Finset ℕ, σ ⊆ s → x ∈ cone σ V → τ.card ≤ σ.card) := by
  sorry
